#!/bin/bash

echo "PORT=$PORT
HOST=$HOST
DB_URL=$DB_URL
INTERVAL_VYPISU_DNY=$INTERVAL_VYPISU_DNY
STAG_URL=$STAG_URL
MIN_TIME_ODZAPIS=$MIN_TIME_ODZAPIS
INTERVAL_ZOBRAZENI_HODINY=$INTERVAL_ZOBRAZENI_HODINY" > /home/py/laborky/.env

exec "$@"

